name: Create Release

on:
   push:
      tags:
         - 'v[0-9]+.[0-9]+.[0-9]+'

   workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         -  name: Get Changelog
            id: changelog
            run: |
               npm ci
               CHANGELOG=$(node script/get-changelog.js --tag ${{github.ref_name}})
               echo "Changelog is:"
               echo "$CHANGELOG"
               echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

         -  name: Build
            run: |
               npm ci
               npm run release

         -  name: Zip
            run: |
               pushd dist/wfrp4e-lords-of-naggaroth
               zip -r ../wfrp4e-lords-of-naggaroth.zip .
               popd

         -  name: Create Release
            run: |
               gh release create "${{github.ref_name}}" --title "${{github.ref_name}}" --notes "${{env.CHANGELOG}}" dist/wfrp4e-lords-of-naggaroth.zip dist/wfrp4e-lords-of-naggaroth/module.json
            env:
               GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
