name: Create Release

on:
   push:
      branches: ["dev"]
   workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         -  name: Build
            run: |
               npm i
               npm run release

         -  name: Zip
            run: |
               pushd dist/wfrp4e-lords-of-naggaroth
               zip -r ../wfrp4e-lords-of-naggaroth.zip .
               popd

         -  name: Create Release
            run: |
               gh release create "dev-${{github.run_number}}" --title "dev-${{github.run_number}}" --notes "dev build ${{github.run_number}}" dist/wfrp4e-lords-of-naggaroth.zip dist/wfrp4e-lords-of-naggaroth/module.json
            env:
               GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
